version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www:ro
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
      - redis
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    extra_hosts:
      - host.docker.internal:host-gateway

  postgres:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - database_data:/var/lib/postgresql/data:rw
#      - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "54321:5432"
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  database_data:
